[project]
name = "land-price-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=4.3.0",
    "fastapi>=0.115.12",
    "google-generativeai>=0.8.5",
    "jose>=1.0.0",
    "mysql-connector-python>=9.3.0",
    "mysqlclient>=2.2.7",
    "passlib>=1.7.4",
    "pydantic-settings>=2.11.0",
    "pykakao>=0.0.7",
    "python-dotenv>=1.1.0",
    "python-multipart>=0.0.20",
    "pytz>=2025.2",
    "ruff>=0.12.2",
    "scikit-learn>=1.6.1",
    "sqlalchemy>=2.0.40",
    "uvicorn>=0.34.2",
    "xgboost>=3.0.0",
    "xmltodict>=0.14.2",
]

[tool.ruff]
select = ["E", "W", "F", "I", "B", "C4", "UP", "SIM"]
ignore = ["E203"]
line-length = 100
target-version = "py313"
