"""Add region_stat table

Revision ID: 45443fb76a87
Revises: 27a9c0bbbf15
Create Date: 2025-06-24 08:38:27.719249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45443fb76a87'
down_revision: Union[str, None] = '27a9c0bbbf15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_stat',
    sa.Column('pnu', sa.String(length=10), nullable=False, comment='행정구역 PNU prefix (10자리)'),
    sa.Column('avg_predicted_price', sa.Float(), nullable=False, comment='해당 행정구역의 평균 예측 토지가격 (원)'),
    sa.Column('avg_official_price', sa.Float(), nullable=False, comment='해당 행정구역의 평균 공시지가 (원)'),
    sa.Column('price_ratio', sa.Float(), nullable=False, comment='예측가 / 공시지가 비율 (%)'),
    sa.Column('valid_count', sa.Integer(), nullable=False, comment='유효한 예측가를 가진 토지 수 (0 초과, None 제외)'),
    sa.PrimaryKeyConstraint('pnu')
    )
    op.drop_index('idx_lat_lng', table_name='land_listing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_lat_lng', 'land_listing', ['lat', 'lng'], unique=False)
    op.drop_table('region_stat')
    # ### end Alembic commands ###
