"""init

Revision ID: 47d03353d458
Revises: 
Create Date: 2025-04-22 23:33:03.094318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47d03353d458'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_coordinate')
    op.drop_table('listing')
    op.drop_table('land_info')
    op.drop_table('geometry_data')
    op.drop_table('trade_history')
    op.drop_table('land_report')
    op.alter_column('user', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='사용자 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(),
               comment='사용자 역할 (1: 일반 사용자, 2: 관리자 등)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               comment='사용자 이메일',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment='사용자 비밀번호',
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=20),
               comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               comment='사용자 닉네임',
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='사용자 전화번호',
               existing_nullable=True)
    op.alter_column('user', 'phone_verified',
               existing_type=mysql.TINYINT(display_width=1),
               comment='전화번호 인증 여부',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'profile_image_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='프로필 이미지 URL',
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'modified_at',
               existing_type=mysql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'last_login',
               existing_type=mysql.TIMESTAMP(),
               comment='마지막 로그인 일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.alter_column('user_favorite_land', 'like_id',
               existing_type=mysql.INTEGER(),
               comment='좋아요 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_favorite_land', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='사용자 ID',
               existing_nullable=False)
    op.alter_column('user_favorite_land', 'pnu',
               existing_type=mysql.VARCHAR(length=20),
               comment='PNU 코드',
               existing_nullable=False)
    op.create_index(op.f('ix_user_favorite_land_pnu'), 'user_favorite_land', ['pnu'], unique=False)
    op.create_index(op.f('ix_user_favorite_land_user_id'), 'user_favorite_land', ['user_id'], unique=False)
    op.drop_constraint('user_favorite_land_ibfk_2', 'user_favorite_land', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_favorite_land_ibfk_2', 'user_favorite_land', 'land_info', ['pnu'], ['pnu'])
    op.drop_index(op.f('ix_user_favorite_land_user_id'), table_name='user_favorite_land')
    op.drop_index(op.f('ix_user_favorite_land_pnu'), table_name='user_favorite_land')
    op.alter_column('user_favorite_land', 'pnu',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='PNU 코드',
               existing_nullable=False)
    op.alter_column('user_favorite_land', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='사용자 ID',
               existing_nullable=False)
    op.alter_column('user_favorite_land', 'like_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='좋아요 ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'last_login',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='마지막 로그인 일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'modified_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'profile_image_url',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='프로필 이미지 URL',
               existing_nullable=True)
    op.alter_column('user', 'phone_verified',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='전화번호 인증 여부',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='사용자 전화번호',
               existing_nullable=True)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='사용자 닉네임',
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='사용자 비밀번호',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='사용자 이메일',
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='사용자 역할 (1: 일반 사용자, 2: 관리자 등)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='사용자 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table('land_report',
    sa.Column('report_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pnu', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('report', mysql.TEXT(), nullable=False),
    sa.Column('like', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('dislike', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('generated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['land_info.pnu'], name='land_report_ibfk_1'),
    sa.PrimaryKeyConstraint('report_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('trade_history',
    sa.Column('trade_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pnu', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('land_classification', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('land_zoning', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('deal_year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deal_month', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deal_price', mysql.FLOAT(), nullable=False),
    sa.Column('deal_area', mysql.FLOAT(), nullable=False),
    sa.Column('deal_type', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('trade_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('geometry_data',
    sa.Column('pnu', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('centroid_lat', mysql.DECIMAL(precision=17, scale=14), nullable=False),
    sa.Column('centroid_lng', mysql.DECIMAL(precision=17, scale=14), nullable=False),
    sa.Column('multi_polygon', mysql.LONGTEXT(), nullable=False),
    sa.PrimaryKeyConstraint('pnu'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('land_info',
    sa.Column('pnu', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('land_feature_stdr_year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('official_land_price', mysql.FLOAT(), nullable=False),
    sa.Column('predict_land_price', mysql.FLOAT(), nullable=True),
    sa.Column('land_classification', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('land_zoning', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('land_use_situation', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('land_register', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('land_area', mysql.FLOAT(), nullable=False),
    sa.Column('land_height', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('land_form', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('road_side', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('land_uses', mysql.TEXT(), nullable=True),
    sa.Column('generated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('predicted_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('pnu'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('listing',
    sa.Column('listing_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pnu', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('lat', mysql.DECIMAL(precision=17, scale=14), nullable=False),
    sa.Column('lng', mysql.DECIMAL(precision=17, scale=14), nullable=False),
    sa.Column('area', mysql.FLOAT(), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('summary', mysql.TEXT(), nullable=False),
    sa.Column('registered_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['land_info.pnu'], name='listing_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='listing_ibfk_1'),
    sa.PrimaryKeyConstraint('listing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('region_coordinate',
    sa.Column('pnu', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('region', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lat', mysql.DECIMAL(precision=17, scale=14), nullable=False),
    sa.Column('lng', mysql.DECIMAL(precision=17, scale=14), nullable=False),
    sa.PrimaryKeyConstraint('pnu'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
