"""Add latlng column in land_info

Revision ID: 53cf2deb5913
Revises: 40a1c80ef2f9
Create Date: 2025-06-27 16:51:50.503510

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53cf2deb5913'
down_revision: str | None = '40a1c80ef2f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_info', sa.Column('lat', sa.Numeric(precision=17, scale=14), nullable=False, comment='위도 (Latitude)'))
    op.add_column('land_info', sa.Column('lng', sa.Numeric(precision=17, scale=14), nullable=False, comment='경도 (Longitude)'))
    op.drop_index('idx_region_coordinate_lat_lng_type', table_name='region_coordinate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_region_coordinate_lat_lng_type', 'region_coordinate', ['lat', 'lng', 'type'], unique=False)
    op.drop_column('land_info', 'lng')
    op.drop_column('land_info', 'lat')
    # ### end Alembic commands ###
