"""add new model

Revision ID: 7144c7cf815e
Revises: 47d03353d458
Create Date: 2025-04-26 00:47:49.166962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7144c7cf815e'
down_revision: Union[str, None] = '47d03353d458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_trade_history',
    sa.Column('trade_id', sa.Integer(), autoincrement=True, nullable=False, comment='거래 고유 ID'),
    sa.Column('pnu', sa.String(length=20), nullable=False, comment='PNU 코드 (토지 고유 식별자)'),
    sa.Column('land_cls', sa.String(length=10), nullable=False, comment='지목 (토지 분류)'),
    sa.Column('land_zoning', sa.String(length=20), nullable=False, comment='용도지역'),
    sa.Column('deal_year', sa.Integer(), nullable=False, comment='거래 연도'),
    sa.Column('deal_month', sa.Integer(), nullable=False, comment='거래 월'),
    sa.Column('deal_price', sa.Float(), nullable=False, comment='거래 금액 (만원 단위일 가능성 있음)'),
    sa.Column('deal_area', sa.Float(), nullable=False, comment='거래 면적 (㎡)'),
    sa.Column('deal_type', sa.String(length=10), nullable=True, comment='거래 유형 (예: 매매/교환 등)'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_table('land_listing',
    sa.Column('listing_id', sa.Integer(), autoincrement=True, nullable=False, comment='매물 고유 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='등록한 사용자 ID'),
    sa.Column('pnu', sa.String(length=20), nullable=False, comment='PNU 코드 (토지 고유 식별자)'),
    sa.Column('lat', sa.Numeric(precision=17, scale=14), nullable=False, comment='위도 (Latitude)'),
    sa.Column('lng', sa.Numeric(precision=17, scale=14), nullable=False, comment='경도 (Longitude)'),
    sa.Column('area', sa.Float(), nullable=False, comment='면적 (㎡)'),
    sa.Column('price', sa.Float(), nullable=False, comment='등록 가격 (단위: 원)'),
    sa.Column('summary', sa.Text(), nullable=False, comment='매물 요약 설명'),
    sa.Column('registered_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='등록 시각'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_land_listing_pnu'), 'land_listing', ['pnu'], unique=False)
    op.create_index(op.f('ix_land_listing_user_id'), 'land_listing', ['user_id'], unique=False)
    op.create_table('user_land_report_reaction',
    sa.Column('reaction_id', sa.Integer(), autoincrement=True, nullable=False, comment='반응 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('report_id', sa.Integer(), nullable=False, comment='분석서 ID'),
    sa.Column('reaction_type', sa.Enum('LIKE', 'DISLIKE', name='reaction_type_enum'), nullable=False, comment='반응 종류 (like/dislike)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True, comment='반응 생성일시'),
    sa.ForeignKeyConstraint(['report_id'], ['land_report.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reaction_id')
    )
    op.create_index(op.f('ix_user_land_report_reaction_report_id'), 'user_land_report_reaction', ['report_id'], unique=False)
    op.create_index(op.f('ix_user_land_report_reaction_user_id'), 'user_land_report_reaction', ['user_id'], unique=False)
    op.drop_table('trade_history')
    op.drop_table('listing')
    op.alter_column('geometry_data', 'pnu',
               existing_type=mysql.VARCHAR(length=10),
               comment='PNU 코드 (행정구역 또는 개별 필지 식별자)',
               existing_nullable=False)
    op.alter_column('geometry_data', 'centroid_lat',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment='중심 위도 (Latitude) - 소수점 14자리까지 정밀도 확보',
               existing_nullable=False)
    op.alter_column('geometry_data', 'centroid_lng',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment='중심 경도 (Longitude) - 소수점 14자리까지 정밀도 확보',
               existing_nullable=False)
    op.alter_column('geometry_data', 'multi_polygon',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               comment='다각형 좌표 (GeoJSON 형식의 MultiPolygon 문자열)',
               existing_nullable=False)
    op.add_column('land_info', sa.Column('official_price', sa.Float(), nullable=False, comment='공시지가 (원)'))
    op.add_column('land_info', sa.Column('predicted_price', sa.Float(), nullable=True, comment='예측된 ㅈ토지가격 (원)'))
    op.add_column('land_info', sa.Column('land_cls', sa.String(length=10), nullable=False, comment='지목 (토지 분류)'))
    op.add_column('land_info', sa.Column('land_usage', sa.String(length=20), nullable=False, comment='토지이용 상황'))
    op.add_column('land_info', sa.Column('land_reg', sa.String(length=10), nullable=False, comment='토지 필지 (일반/산)'))
    op.add_column('land_info', sa.Column('use_plan', sa.Text(), nullable=True, comment='토지 이용 계획'))
    op.add_column('land_info', sa.Column('land_stdr_year', sa.String(length=4), nullable=False, comment='토지특성 기준년도'))
    op.add_column('land_info', sa.Column('land_stdr_month', sa.String(length=2), nullable=False, comment='토지특성 기준월'))
    op.add_column('land_info', sa.Column('last_predicted_date', sa.TIMESTAMP(), nullable=True, comment='마지막 예측 일시'))
    op.add_column('land_info', sa.Column('like_count', sa.Integer(), nullable=False, comment='좋아요 수'))
    op.alter_column('land_info', 'pnu',
               existing_type=mysql.VARCHAR(length=20),
               comment='필지번호 (PNU)',
               existing_nullable=False)
    op.alter_column('land_info', 'land_zoning',
               existing_type=mysql.VARCHAR(length=20),
               comment='용도지역',
               existing_nullable=False)
    op.alter_column('land_info', 'land_area',
               existing_type=mysql.FLOAT(),
               comment='토지 면적 (㎡)',
               existing_nullable=False)
    op.alter_column('land_info', 'land_height',
               existing_type=mysql.VARCHAR(length=10),
               comment='지형 높이',
               existing_nullable=False)
    op.alter_column('land_info', 'land_form',
               existing_type=mysql.VARCHAR(length=10),
               comment='지형 형태',
               existing_nullable=False)
    op.alter_column('land_info', 'road_side',
               existing_type=mysql.VARCHAR(length=10),
               comment='도로 접면 여부',
               existing_nullable=False)
    op.drop_column('land_info', 'official_land_price')
    op.drop_column('land_info', 'land_register')
    op.drop_column('land_info', 'predict_land_price')
    op.drop_column('land_info', 'land_uses')
    op.drop_column('land_info', 'land_feature_stdr_year')
    op.drop_column('land_info', 'predicted_at')
    op.drop_column('land_info', 'land_use_situation')
    op.drop_column('land_info', 'land_classification')
    op.drop_column('land_info', 'generated_at')
    op.add_column('land_report', sa.Column('content', sa.Text(), nullable=False, comment='생성된 토지 분석서 텍스트'))
    op.add_column('land_report', sa.Column('like_count', sa.Integer(), nullable=False, comment='좋아요 수'))
    op.add_column('land_report', sa.Column('dislike_count', sa.Integer(), nullable=False, comment='싫어요 수'))
    op.alter_column('land_report', 'report_id',
               existing_type=mysql.INTEGER(),
               comment='분석서 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('land_report', 'pnu',
               existing_type=mysql.VARCHAR(length=20),
               comment='PNU 코드 (토지 고유 식별자)',
               existing_nullable=False)
    op.alter_column('land_report', 'generated_at',
               existing_type=mysql.TIMESTAMP(),
               comment='리포트 생성 시각',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('land_report_ibfk_1', 'land_report', type_='foreignkey')
    op.drop_column('land_report', 'like')
    op.drop_column('land_report', 'dislike')
    op.drop_column('land_report', 'report')
    op.alter_column('region_coordinate', 'pnu',
               existing_type=mysql.VARCHAR(length=10),
               comment='PNU 코드 (행정구역 고유 식별자)',
               existing_nullable=False)
    op.alter_column('region_coordinate', 'type',
               existing_type=mysql.VARCHAR(length=12),
               comment='행정구역 타입 (sido/sigungu/eupmyeondong)',
               existing_nullable=False)
    op.alter_column('region_coordinate', 'region',
               existing_type=mysql.VARCHAR(length=50),
               comment='행정구역 명 (ex: 서울특별시 강남구 역삼동)',
               existing_nullable=False)
    op.alter_column('region_coordinate', 'lat',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment='위도 (Latitude)',
               existing_nullable=False)
    op.alter_column('region_coordinate', 'lng',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment='경도 (Longitude)',
               existing_nullable=False)
    op.alter_column('user', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='사용자 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('ADMIN', 'GENERAL', 'PREMIUM', name='user_type_enum'),
               comment='사용자 역할 (관리자/일반회원/유료회원)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               comment='사용자 이메일',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment='사용자 비밀번호',
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=20),
               comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               comment='사용자 닉네임',
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='사용자 전화번호',
               existing_nullable=True)
    op.alter_column('user', 'phone_verified',
               existing_type=mysql.TINYINT(display_width=1),
               comment='전화번호 인증 여부',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'profile_image_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='프로필 이미지 URL',
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'modified_at',
               existing_type=mysql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'last_login',
               existing_type=mysql.TIMESTAMP(),
               comment='마지막 로그인 일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.alter_column('user_favorite_land', 'like_id',
               existing_type=mysql.INTEGER(),
               comment='좋아요 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_favorite_land', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='사용자 ID',
               existing_nullable=False)
    op.alter_column('user_favorite_land', 'pnu',
               existing_type=mysql.VARCHAR(length=20),
               comment='PNU 코드',
               existing_nullable=False)
    op.create_index(op.f('ix_user_favorite_land_pnu'), 'user_favorite_land', ['pnu'], unique=False)
    op.create_index(op.f('ix_user_favorite_land_user_id'), 'user_favorite_land', ['user_id'], unique=False)
    op.drop_constraint('user_favorite_land_ibfk_2', 'user_favorite_land', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_favorite_land_ibfk_2', 'user_favorite_land', 'land_info', ['pnu'], ['pnu'])
    op.drop_index(op.f('ix_user_favorite_land_user_id'), table_name='user_favorite_land')
    op.drop_index(op.f('ix_user_favorite_land_pnu'), table_name='user_favorite_land')
    op.alter_column('user_favorite_land', 'pnu',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='PNU 코드',
               existing_nullable=False)
    op.alter_column('user_favorite_land', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='사용자 ID',
               existing_nullable=False)
    op.alter_column('user_favorite_land', 'like_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='좋아요 ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'last_login',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='마지막 로그인 일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'modified_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'profile_image_url',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='프로필 이미지 URL',
               existing_nullable=True)
    op.alter_column('user', 'phone_verified',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='전화번호 인증 여부',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='사용자 전화번호',
               existing_nullable=True)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='사용자 닉네임',
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='사용자 비밀번호',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='사용자 이메일',
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.Enum('ADMIN', 'GENERAL', 'PREMIUM', name='user_type_enum'),
               type_=mysql.INTEGER(),
               comment=None,
               existing_comment='사용자 역할 (관리자/일반회원/유료회원)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='사용자 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('region_coordinate', 'lng',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment=None,
               existing_comment='경도 (Longitude)',
               existing_nullable=False)
    op.alter_column('region_coordinate', 'lat',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment=None,
               existing_comment='위도 (Latitude)',
               existing_nullable=False)
    op.alter_column('region_coordinate', 'region',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='행정구역 명 (ex: 서울특별시 강남구 역삼동)',
               existing_nullable=False)
    op.alter_column('region_coordinate', 'type',
               existing_type=mysql.VARCHAR(length=12),
               comment=None,
               existing_comment='행정구역 타입 (sido/sigungu/eupmyeondong)',
               existing_nullable=False)
    op.alter_column('region_coordinate', 'pnu',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='PNU 코드 (행정구역 고유 식별자)',
               existing_nullable=False)
    op.add_column('land_report', sa.Column('report', mysql.TEXT(), nullable=False))
    op.add_column('land_report', sa.Column('dislike', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('land_report', sa.Column('like', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.create_foreign_key('land_report_ibfk_1', 'land_report', 'land_info', ['pnu'], ['pnu'])
    op.alter_column('land_report', 'generated_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='리포트 생성 시각',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('land_report', 'pnu',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='PNU 코드 (토지 고유 식별자)',
               existing_nullable=False)
    op.alter_column('land_report', 'report_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='분석서 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('land_report', 'dislike_count')
    op.drop_column('land_report', 'like_count')
    op.drop_column('land_report', 'content')
    op.add_column('land_info', sa.Column('generated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('land_info', sa.Column('land_classification', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('land_info', sa.Column('land_use_situation', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('land_info', sa.Column('predicted_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('land_info', sa.Column('land_feature_stdr_year', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('land_info', sa.Column('land_uses', mysql.TEXT(), nullable=True))
    op.add_column('land_info', sa.Column('predict_land_price', mysql.FLOAT(), nullable=True))
    op.add_column('land_info', sa.Column('land_register', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('land_info', sa.Column('official_land_price', mysql.FLOAT(), nullable=False))
    op.alter_column('land_info', 'road_side',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='도로 접면 여부',
               existing_nullable=False)
    op.alter_column('land_info', 'land_form',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='지형 형태',
               existing_nullable=False)
    op.alter_column('land_info', 'land_height',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='지형 높이',
               existing_nullable=False)
    op.alter_column('land_info', 'land_area',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='토지 면적 (㎡)',
               existing_nullable=False)
    op.alter_column('land_info', 'land_zoning',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='용도지역',
               existing_nullable=False)
    op.alter_column('land_info', 'pnu',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='필지번호 (PNU)',
               existing_nullable=False)
    op.drop_column('land_info', 'like_count')
    op.drop_column('land_info', 'last_predicted_date')
    op.drop_column('land_info', 'land_stdr_month')
    op.drop_column('land_info', 'land_stdr_year')
    op.drop_column('land_info', 'use_plan')
    op.drop_column('land_info', 'land_reg')
    op.drop_column('land_info', 'land_usage')
    op.drop_column('land_info', 'land_cls')
    op.drop_column('land_info', 'predicted_price')
    op.drop_column('land_info', 'official_price')
    op.alter_column('geometry_data', 'multi_polygon',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               comment=None,
               existing_comment='다각형 좌표 (GeoJSON 형식의 MultiPolygon 문자열)',
               existing_nullable=False)
    op.alter_column('geometry_data', 'centroid_lng',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment=None,
               existing_comment='중심 경도 (Longitude) - 소수점 14자리까지 정밀도 확보',
               existing_nullable=False)
    op.alter_column('geometry_data', 'centroid_lat',
               existing_type=mysql.DECIMAL(precision=17, scale=14),
               comment=None,
               existing_comment='중심 위도 (Latitude) - 소수점 14자리까지 정밀도 확보',
               existing_nullable=False)
    op.alter_column('geometry_data', 'pnu',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='PNU 코드 (행정구역 또는 개별 필지 식별자)',
               existing_nullable=False)
    op.create_table('listing',
    sa.Column('listing_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pnu', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('lat', mysql.DECIMAL(precision=17, scale=14), nullable=False),
    sa.Column('lng', mysql.DECIMAL(precision=17, scale=14), nullable=False),
    sa.Column('area', mysql.FLOAT(), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('summary', mysql.TEXT(), nullable=False),
    sa.Column('registered_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['land_info.pnu'], name='listing_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='listing_ibfk_1'),
    sa.PrimaryKeyConstraint('listing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('trade_history',
    sa.Column('trade_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pnu', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('land_classification', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('land_zoning', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('deal_year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deal_month', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deal_price', mysql.FLOAT(), nullable=False),
    sa.Column('deal_area', mysql.FLOAT(), nullable=False),
    sa.Column('deal_type', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('trade_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_user_land_report_reaction_user_id'), table_name='user_land_report_reaction')
    op.drop_index(op.f('ix_user_land_report_reaction_report_id'), table_name='user_land_report_reaction')
    op.drop_table('user_land_report_reaction')
    op.drop_index(op.f('ix_land_listing_user_id'), table_name='land_listing')
    op.drop_index(op.f('ix_land_listing_pnu'), table_name='land_listing')
    op.drop_table('land_listing')
    op.drop_table('land_trade_history')
    # ### end Alembic commands ###
