"""Alter land_owner and land_listing table

Revision ID: 720b470f2ec8
Revises: e57c468c3f8f
Create Date: 2025-07-08 17:24:55.077936

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '720b470f2ec8'
down_revision: str | None = 'e57c468c3f8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_land_listing_pnu', table_name='land_listing')
    op.drop_column('land_listing', 'pnu')
    op.drop_column('land_listing', 'lat')
    op.drop_column('land_listing', 'lng')
    op.add_column('land_owner', sa.Column('pnu', sa.String(length=20), nullable=False, comment='PNU 코드 (토지 고유 식별자)'))
    op.add_column('land_owner', sa.Column('lat', sa.Numeric(precision=17, scale=14), nullable=False, comment='위도 (Latitude)'))
    op.add_column('land_owner', sa.Column('lng', sa.Numeric(precision=17, scale=14), nullable=False, comment='경도 (Longitude)'))
    op.create_index(op.f('ix_land_owner_pnu'), 'land_owner', ['pnu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_land_owner_pnu'), table_name='land_owner')
    op.drop_column('land_owner', 'lng')
    op.drop_column('land_owner', 'lat')
    op.drop_column('land_owner', 'pnu')
    op.add_column('land_listing', sa.Column('lng', mysql.DECIMAL(precision=17, scale=14), nullable=False, comment='경도 (Longitude)'))
    op.add_column('land_listing', sa.Column('lat', mysql.DECIMAL(precision=17, scale=14), nullable=False, comment='위도 (Latitude)'))
    op.add_column('land_listing', sa.Column('pnu', mysql.VARCHAR(length=20), nullable=False, comment='PNU 코드 (토지 고유 식별자)'))
    op.create_index('ix_land_listing_pnu', 'land_listing', ['pnu'], unique=False)
    # ### end Alembic commands ###
