"""Alter land_auction table

Revision ID: 7a2363d746b6
Revises: 8ad8f4e34622
Create Date: 2025-07-04 11:03:49.089318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a2363d746b6'
down_revision: Union[str, None] = '8ad8f4e34622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_auction', sa.Column('land_detail', sa.Text(), nullable=True, comment='토지 설명'))
    op.alter_column('land_auction', 'auction_time',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_comment='매각 시간',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('land_auction', 'auction_time',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_comment='매각 시간',
               existing_nullable=False)
    op.drop_column('land_auction', 'land_detail')
    # ### end Alembic commands ###
