"""Add land_auction table

Revision ID: 8ad8f4e34622
Revises: bef1d7f0a117
Create Date: 2025-07-04 10:15:50.569558

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ad8f4e34622'
down_revision: str | None = 'bef1d7f0a117'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_auction',
    sa.Column('doc_id', sa.String(length=24), nullable=False, comment='경매 고유 ID'),
    sa.Column('pnu', sa.String(length=20), nullable=False, comment='PNU 코드 (토지 고유 식별자)'),
    sa.Column('case_cd', sa.String(length=15), nullable=False, comment='사건번호'),
    sa.Column('obj_cd', sa.Integer(), nullable=False, comment='물건번호'),
    sa.Column('obj_type', sa.String(length=100), nullable=False, comment='물건종류'),
    sa.Column('appraisal_price', sa.Float(), nullable=False, comment='감정평가액'),
    sa.Column('min_sale_price', sa.Float(), nullable=False, comment='최저입찰가'),
    sa.Column('auction_date', sa.Integer(), nullable=False, comment='매각 기일'),
    sa.Column('auction_time', sa.Float(), nullable=False, comment='매각 시간'),
    sa.Column('court_in_charge', sa.String(length=20), nullable=False, comment='담당법원'),
    sa.Column('court_detail', sa.String(length=20), nullable=False, comment='담당법원 부서'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_land_auction_pnu'), 'land_auction', ['pnu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_land_auction_pnu'), table_name='land_auction')
    op.drop_table('land_auction')
    # ### end Alembic commands ###
