"""fix user role

Revision ID: 9201e756de0c
Revises: 271e4961d14f
Create Date: 2025-04-26 00:59:08.198051

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9201e756de0c'
down_revision: str | None = '271e4961d14f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('ADMIN', 'GENERAL', 'PREMIUM', name='user_type_enum'),
               comment='사용자 역할 (관리자/일반회원/유료회원)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               comment='사용자 이메일',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment='사용자 비밀번호',
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=20),
               comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               comment='사용자 닉네임',
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='사용자 전화번호',
               existing_nullable=True)
    op.alter_column('user', 'phone_verified',
               existing_type=mysql.TINYINT(display_width=1),
               comment='전화번호 인증 여부',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'profile_image_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='프로필 이미지 URL',
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'modified_at',
               existing_type=mysql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'last_login',
               existing_type=mysql.TIMESTAMP(),
               comment='마지막 로그인 일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.alter_column('user_favorite_land', 'like_id',
               existing_type=mysql.INTEGER(),
               comment='좋아요 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_favorite_land', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='사용자 ID',
               existing_nullable=False)
    op.alter_column('user_favorite_land', 'pnu',
               existing_type=mysql.VARCHAR(length=20),
               comment='PNU 코드',
               existing_nullable=False)
    op.create_index(op.f('ix_user_favorite_land_pnu'), 'user_favorite_land', ['pnu'], unique=False)
    op.create_index(op.f('ix_user_favorite_land_user_id'), 'user_favorite_land', ['user_id'], unique=False)
    op.drop_constraint('user_favorite_land_ibfk_2', 'user_favorite_land', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_favorite_land_ibfk_2', 'user_favorite_land', 'land_info', ['pnu'], ['pnu'])
    op.drop_index(op.f('ix_user_favorite_land_user_id'), table_name='user_favorite_land')
    op.drop_index(op.f('ix_user_favorite_land_pnu'), table_name='user_favorite_land')
    op.alter_column('user_favorite_land', 'pnu',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='PNU 코드',
               existing_nullable=False)
    op.alter_column('user_favorite_land', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='사용자 ID',
               existing_nullable=False)
    op.alter_column('user_favorite_land', 'like_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='좋아요 ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'last_login',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='마지막 로그인 일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'modified_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'profile_image_url',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='프로필 이미지 URL',
               existing_nullable=True)
    op.alter_column('user', 'phone_verified',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='전화번호 인증 여부',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='사용자 전화번호',
               existing_nullable=True)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='사용자 닉네임',
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='사용자 비밀번호',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='사용자 이메일',
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.Enum('ADMIN', 'GENERAL', 'PREMIUM', name='user_type_enum'),
               type_=mysql.INTEGER(),
               comment=None,
               existing_comment='사용자 역할 (관리자/일반회원/유료회원)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###
