"""fix land stdr year and month

Revision ID: 93aad4dcb7a6
Revises: 618a3553fec5
Create Date: 2025-04-26 01:18:16.059505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93aad4dcb7a6'
down_revision: Union[str, None] = '618a3553fec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_info', sa.Column('stdr_year', sa.String(length=4), nullable=False, comment='토지특성 기준년도'))
    op.add_column('land_info', sa.Column('stdr_month', sa.String(length=2), nullable=False, comment='토지특성 기준월'))
    op.drop_column('land_info', 'land_stdr_month')
    op.drop_column('land_info', 'land_stdr_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_info', sa.Column('land_stdr_year', mysql.VARCHAR(length=4), nullable=False, comment='토지특성 기준년도'))
    op.add_column('land_info', sa.Column('land_stdr_month', mysql.VARCHAR(length=2), nullable=False, comment='토지특성 기준월'))
    op.drop_column('land_info', 'stdr_month')
    op.drop_column('land_info', 'stdr_year')
    # ### end Alembic commands ###
