"""Add auction tables

Revision ID: bef1d7f0a117
Revises: 53cf2deb5913
Create Date: 2025-06-29 10:29:31.769166

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'bef1d7f0a117'
down_revision: str | None = '53cf2deb5913'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
