"""Add auction tables

Revision ID: bef1d7f0a117
Revises: 53cf2deb5913
Create Date: 2025-06-29 10:29:31.769166

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'bef1d7f0a117'
down_revision: Union[str, None] = '53cf2deb5913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
