"""Add land_owner table

Revision ID: e57c468c3f8f
Revises: f3184de61c4f
Create Date: 2025-07-08 16:42:29.680676

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e57c468c3f8f'
down_revision: str | None = 'f3184de61c4f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_owner',
    sa.Column('owner_id', sa.Integer(), autoincrement=True, nullable=False, comment='소유 매물 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='소유주 사용자 ID'),
    sa.Column('registered_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='등록 시각'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index(op.f('ix_land_owner_user_id'), 'land_owner', ['user_id'], unique=False)
    op.add_column('land_listing', sa.Column('owner_id', sa.Integer(), nullable=False, comment='등록한 소유 토지 ID'))
    op.create_foreign_key(None, 'land_listing', 'land_owner', ['owner_id'], ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'land_listing', type_='foreignkey')
    op.drop_column('land_listing', 'owner_id')
    op.drop_index(op.f('ix_land_owner_user_id'), table_name='land_owner')
    op.drop_table('land_owner')
    # ### end Alembic commands ###
