"""Add land_auction table lat, lng

Revision ID: f3184de61c4f
Revises: 7a2363d746b6
Create Date: 2025-07-06 10:16:10.401414

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3184de61c4f'
down_revision: str | None = '7a2363d746b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_auction', sa.Column('lat', sa.Numeric(precision=17, scale=14), nullable=False, comment='위도 (Latitude)'))
    op.add_column('land_auction', sa.Column('lng', sa.Numeric(precision=17, scale=14), nullable=False, comment='경도 (Longitude)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land_auction', 'lng')
    op.drop_column('land_auction', 'lat')
    # ### end Alembic commands ###
